export { isBlocked } from "./blocklist";
export { detectArchetype } from "./archetype";
export type { Archetype } from "./archetype";
export { fetchRepoTree } from "./github/tree";
export { fetchBlobsBatch } from "./github/blobs";
export type { FileBlob } from "./github/blobs";
export { fetchRepoStats } from "./github/stats";
export { groupByModule } from "./chunking/modules";
export type { ModuleGroup } from "./chunking/modules";
export { extractSymbolChunks } from "./chunking/symbols";
export type { RawChunk } from "./chunking/symbols";
export { coalesceChunks } from "./chunking/coalesce";
export { embedChunks } from "./embeddings";
export type { EmbeddedChunk } from "./embeddings";
export { ensureIndex, upsertChunks, queryVectors } from "./vector-store";
