export { isBlocked } from "./blocklist.js";
export { detectArchetype } from "./archetype.js";
export type { Archetype } from "./archetype.js";
export { fetchRepoTree } from "./github/tree.js";
export { fetchBlobsBatch } from "./github/blobs.js";
export type { FileBlob } from "./github/blobs.js";
export { fetchRepoStats } from "./github/stats.js";
export { groupByModule } from "./chunking/modules.js";
export type { ModuleGroup } from "./chunking/modules.js";
export { extractSymbolChunks } from "./chunking/symbols.js";
export type { RawChunk } from "./chunking/symbols.js";
export { coalesceChunks } from "./chunking/coalesce.js";
export { embedChunks } from "./embeddings.js";
export type { EmbeddedChunk } from "./embeddings.js";
export { ensureIndex, upsertChunks, queryVectors } from "./vector-store.js";
